In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
scalar = tf.constant(7)
scalar

Metal device set to: Apple M1 Pro


2022-10-16 08:37:05.679727: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-10-16 08:37:05.680053: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
matrix2 = tf.constant([[10.,7.], [7.,10.],[8.,9.]], dtype=tf.float16)
matrix2                       

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
matrix2.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [11]:
tensor.ndim

3

Tensorflow variable

In [12]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
vector.ndim

1

In [14]:
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [15]:
matrix.ndim

2

In [16]:
matrix2 = tf.constant([[10.,7.], [7.,10.],[8.,9.]], dtype=tf.float16)
matrix2                       

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [17]:
matrix2.ndim

2

In [18]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [19]:
tensor.ndim

3

# Tensorflow variable

In [20]:
tensorflow_var = tf.Variable([10,7])
tensorflow_const = tf.constant([10,7])
tensorflow_var, tensorflow_const

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
tensorflow_var[0].assign(7)
tensorflow_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
# tensorflow_const[0].assign(7)
# tensorflow_const

## Create random tensor
random tensors are some arbitiry 

In [23]:
random_tensor = tf.random.uniform(
    [128],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf.random.Generator.from_seed(42)

random_tensor2 = tf.random.normal(
    [2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

# random_tensor3 = tf.random.Generator.from_seed(42)

# random_tensor3 = random_tensor2.normal(shape=(3,2))

random_tensor, random_tensor2

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([0.70321774, 0.8357085 , 0.29538095, 0.9284327 , 0.16369092,
        0.7531364 , 0.9591118 , 0.9448811 , 0.5989548 , 0.02085316,
        0.9410002 , 0.5247146 , 0.87824595, 0.6755549 , 0.1349206 ,
        0.6170192 , 0.78303134, 0.82649183, 0.95860803, 0.665514  ,
        0.4254309 , 0.5430386 , 0.05771565, 0.21532094, 0.95732677,
        0.71435916, 0.12459147, 0.6804651 , 0.06946898, 0.00813925,
        0.9216261 , 0.60117066, 0.4487288 , 0.19832456, 0.282153  ,
        0.8986466 , 0.03986335, 0.6346723 , 0.2973914 , 0.8479084 ,
        0.19348264, 0.6926991 , 0.9164152 , 0.98824334, 0.07904351,
        0.3726251 , 0.86478853, 0.02200854, 0.08353531, 0.5055095 ,
        0.48637533, 0.09411597, 0.6266396 , 0.51878965, 0.06440341,
        0.09187639, 0.24311054, 0.6184943 , 0.71212864, 0.5406451 ,
        0.5988209 , 0.5487484 , 0.19415498, 0.7893181 , 0.374254  ,
        0.2516278 , 0.23872757, 0.49433756, 0.3429109 , 0.6082114 ,

## shuffle tensors


In [24]:
unshuff_tensor = tf.constant([[10.,7.], [7.,10.],[8.,9.]], dtype=tf.float16)
unshuff_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [25]:
tf.random.set_seed(42)
tf.random.shuffle(unshuff_tensor)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7., 10.],
       [ 8.,  9.],
       [10.,  7.]], dtype=float16)>

In [26]:
unshuff_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [27]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [28]:
vector.ndim

1

In [29]:
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [30]:
matrix.ndim

2

In [31]:
matrix2 = tf.constant([[10.,7.], [7.,10.],[8.,9.]], dtype=tf.float16)
matrix2                       

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [32]:
matrix2.ndim

2

In [33]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [34]:
tensor.ndim

3

# Tensorflow variable

In [35]:
tensorflow_var = tf.Variable([10,7])
tensorflow_const = tf.constant([10,7])
tensorflow_var, tensorflow_const

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [36]:
tensorflow_var[0].assign(7)
tensorflow_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [37]:
# tensorflow_const[0].assign(7)
# tensorflow_const

## Create random tensor
random tensors are some arbitiry 

In [38]:
random_tensor = tf.random.uniform(
    [128],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf.random.Generator.from_seed(42)

random_tensor2 = tf.random.normal(
    [2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

# random_tensor3 = tf.random.Generator.from_seed(42)

# random_tensor3 = random_tensor2.normal(shape=(3,2))

random_tensor, random_tensor2

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ,
        0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869,
        0.8163481 , 0.65651655, 0.9258256 , 0.2391715 , 0.8365958 ,
        0.04765272, 0.8007157 , 0.8299267 , 0.14328372, 0.8616878 ,
        0.9707202 , 0.6779593 , 0.5641242 , 0.62537   , 0.8653159 ,

## shuffle tensors


In [39]:
unshuff_tensor = tf.constant([[10.,7.], [7.,10.],[8.,9.]], dtype=tf.float16)
unshuff_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [40]:
tf.random.set_seed(42)
tf.random.shuffle(unshuff_tensor)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7., 10.],
       [ 8.,  9.],
       [10.,  7.]], dtype=float16)>

In [41]:
unshuff_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

Setting both golbal and local seed will fix the shuffle

In [42]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [44]:
tf.zeros((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [45]:
import numpy as np

In [47]:
numpy_a = np.arange(1,25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

tensor can be run on gpu numpy array are not that fast on GPU

In [53]:
A = tf.constant(numpy_a, shape=(2,3,4))

In [54]:
tf.constant(numpy_a)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [55]:
tf.constant(numpy_a, shape=(3,8))

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

- shape
- rank
- axis/dimension
- size

In [ ]:
A.dtype, A.shape, tf.rank(A),A, A[0], A[:, :, 0].shape, tf.size(A).numpy()

In [ ]:
A[:, 0, 1 ]

In [ ]:
B = A[..., tf.newaxis]
C = B[..., tf.newaxis]


Alternative to newaxis

In [ ]:
B = tf.expand_dims(A, axis=0)
A,B

### Manipulation tensors
***basic operation***
`+`,`-`, `*`, `/`

In [ ]:
tensor = tf.constant([[10,7], [3,4]])
tensor+10

In [ ]:
tensor -10

In [ ]:
tensor*2

In [ ]:
tensor/2

In [ ]:
#using builtin operator is faster on GPU
tf.multiply(tensor, 2)

In [ ]:
tf.add(tensor, 10)

In [ ]:
tf.subtract(tensor,10)

In [ ]:
tf.divide(tensor, 2)

***Matrix manupliation***

In [ ]:
tensor2 = tf.constant([[2,3],[5,6]])
tensor2

In [ ]:
tensor

In [ ]:
tensor*tensor2

In [ ]:
tf.matmul(tensor, tensor2)


In [ ]:
tensor @ tensor2


In [ ]:
tensor = tf.constant([[10,7,6], [3,4, 5]])
tensor2 = tf.constant([[2,3, 5],[6, 8, 9]])


In [ ]:
tf.matmul(tensor, tensor2)

In [ ]:
tensor2 = tf.reshape(tensor2, shape=(3,2))
tensor2

In [ ]:
tensor @ tensor2

In [ ]:
tensor2 * tf.transpose(tensor)

In [ ]:
tf.tensordot(tensor, tensor2, 1)

### Changing datatype

In [ ]:
B = tf.constant([[10,7], [5,6.]])
B.dtype

In [ ]:
C = tf.constant([[10,7], [5,6]])
C.dtype

In [ ]:
D = tf.cast(B, tf.float16)
D.dtype

Aggreation

In [ ]:
C = tf.constant([[-10,7], [5,6]])


In [ ]:
tf.abs(C)

In [ ]:
E =tf.constant(np.random.randint(0,100, size=50))
E

In [ ]:
tf.reduce_min(E).numpy()

In [ ]:
tf.reduce_max(E).numpy()

In [ ]:
tf.reduce_mean(E).numpy()

In [ ]:
tf.reduce_sum(E).numpy()

In [ ]:
F = tf.cast(E, tf.float32)
tf.math.reduce_variance(F).numpy()

In [ ]:
tf.math.reduce_std(F).numpy()

### Positional max and min

In [ ]:
G = tf.random.uniform(shape=[50])
G

#### arg max 

In [ ]:
tf.argmax(G)

In [ ]:
G[tf.argmax(G)]

In [ ]:
tf.reduce_max(G)

### Squezzing a tensor

In [ ]:
H = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
H

In [ ]:
H_squezzed = tf.squeeze(H)
H_squezzed

### one hot encoding tensors

In [ ]:
some_list = [0,3,5,2]
tf.one_hot(some_list, depth=9)

In [ ]:
tf.one_hot(some_list, on_value="test", off_value="offtest", depth=4)

#### Math operation more

In [ ]:
I = tf.range(0,10)

In [ ]:
tf.square(I)

In [ ]:
tf.sqrt(tf.cast(I, dtype=tf.float32))

In [ ]:
tf.math.log(tf.cast(I, dtype=tf.float32))

#### NUMPY

In [ ]:
J = tf.constant(np.array([1,2,3,4]))

In [ ]:
np.array(J)

In [ ]:
J.numpy()

### tf created using numpy array  are float64

## GPU compare

In [ ]:
tf.config.list_physical_devices()

In [86]:
A[:, 0, 1 ]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 14], dtype=int32)>

In [90]:
B = A[..., tf.newaxis]
C = B[..., tf.newaxis]


Alternative to newaxis

In [94]:
B = tf.expand_dims(A, axis=0)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
 array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]], dtype=int32)>)

### Manipulation tensors
***basic operation***
`+`,`-`, `*`, `/`

In [95]:
tensor = tf.constant([[10,7], [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [96]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [97]:
tensor*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [98]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [102]:
#using builtin operator is faster on GPU
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [103]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [106]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [107]:
tf.divide(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

***Matrix manupliation***

In [116]:
tensor2 = tf.constant([[2,3],[5,6]])
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [113]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [109]:
tensor*tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 21],
       [15, 24]], dtype=int32)>

In [145]:
tf.matmul(tensor, tensor2)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[103, 126],
       [ 66,  78]], dtype=int32)>

In [119]:
tensor @ tensor2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[55, 72],
       [26, 33]], dtype=int32)>

In [129]:
tensor = tf.constant([[10,7,6], [3,4, 5]])
tensor2 = tf.constant([[2,3, 5],[6, 8, 9]])


In [130]:
tf.matmul(tensor, tensor2)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul]

In [136]:
tensor2 = tf.reshape(tensor2, shape=(3,2))
tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [8, 9]], dtype=int32)>

In [134]:
tensor @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[103, 126],
       [ 66,  78]], dtype=int32)>

In [141]:
tensor2 * tf.transpose(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20,  9],
       [35, 24],
       [48, 45]], dtype=int32)>

In [148]:
tf.tensordot(tensor, tensor2, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[103, 126],
       [ 66,  78]], dtype=int32)>

### Changing datatype

In [149]:
B = tf.constant([[10,7], [5,6.]])
B.dtype

tf.float32

In [150]:
C = tf.constant([[10,7], [5,6]])
C.dtype

tf.int32

In [152]:
D = tf.cast(B, tf.float16)
D.dtype

tf.float16

Aggreation

In [153]:
C = tf.constant([[-10,7], [5,6]])


In [154]:
tf.abs(C)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6]], dtype=int32)>

In [158]:
E =tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([35,  9,  9, 15, 21, 79, 98, 21, 93, 14, 67, 42, 11, 59, 34, 49, 50,
       73, 66, 92, 30, 78, 93, 55, 79, 18, 19, 92,  7, 90, 94, 58, 74, 18,
       49, 19, 30, 94, 47, 91, 48, 23, 49, 96, 69, 82, 95, 60, 30, 29])>

In [160]:
tf.reduce_min(E).numpy()

7

In [163]:
tf.reduce_max(E).numpy()

98

In [164]:
tf.reduce_mean(E).numpy()

53

In [167]:
tf.reduce_sum(E).numpy()

2653

In [182]:
F = tf.cast(E, tf.float32)
tf.math.reduce_variance(F).numpy()

879.2564

In [186]:
tf.math.reduce_std(F).numpy()

29.652258

### Positional max and min

In [194]:
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ,
       0.18209696, 0.63791955, 0.27701473, 0.04227114, 0.84219384,
       0.90637195, 0.222556  , 0.9198462 , 0.68789077, 0.42705178,
       0.878158  , 0.6943959 , 0.46567595, 0.52925766, 0.33019018,
       0.12754858, 0.16153514, 0.5085137 , 0.44301772, 0.35205877,
       0.8969147 , 0.24940813, 0.76328313, 0.85935795, 0.08480155,
       0.20418596, 0.28848922, 0.65142167, 0.7106751 , 0.8695041 ,
       0.23745108, 0.6688912 , 0.7115667 , 0.21899498, 0.7702793 ,
       0.45055628, 0.95493364, 0.71695936, 0.98945487, 0.1511141 ,
       0.06240606, 0.15209746, 0.99522185, 0.7830266 , 0.10455871],
      dtype=float32)>

#### arg max 

In [195]:
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [196]:
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99522185>

In [197]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99522185>

### Squezzing a tensor

In [201]:
H = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.43555546, 0.52486527, 0.49674678, 0.06710219, 0.35815144,
           0.5931845 , 0.8396933 , 0.32720697, 0.08762932, 0.0971967 ,
           0.9376564 , 0.18501604, 0.9981525 , 0.82236457, 0.42403674,
           0.05161929, 0.20221865, 0.8313112 , 0.02180374, 0.7716117 ,
           0.43708587, 0.38407493, 0.8155345 , 0.8697617 , 0.1877197 ,
           0.6120846 , 0.01730704, 0.6251298 , 0.9047519 , 0.45837843,
           0.98503745, 0.39521003, 0.4194014 , 0.2234962 , 0.9076545 ,
           0.13453591, 0.3705256 , 0.84200656, 0.86062145, 0.06019282,
           0.2456857 , 0.9456284 , 0.6033411 , 0.66060483, 0.43036914,
           0.7185979 , 0.49352026, 0.1214813 , 0.7401178 , 0.09666443]]]]],
      dtype=float32)>

In [203]:
H_squezzed = tf.squeeze(H)
H_squezzed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.43555546, 0.52486527, 0.49674678, 0.06710219, 0.35815144,
       0.5931845 , 0.8396933 , 0.32720697, 0.08762932, 0.0971967 ,
       0.9376564 , 0.18501604, 0.9981525 , 0.82236457, 0.42403674,
       0.05161929, 0.20221865, 0.8313112 , 0.02180374, 0.7716117 ,
       0.43708587, 0.38407493, 0.8155345 , 0.8697617 , 0.1877197 ,
       0.6120846 , 0.01730704, 0.6251298 , 0.9047519 , 0.45837843,
       0.98503745, 0.39521003, 0.4194014 , 0.2234962 , 0.9076545 ,
       0.13453591, 0.3705256 , 0.84200656, 0.86062145, 0.06019282,
       0.2456857 , 0.9456284 , 0.6033411 , 0.66060483, 0.43036914,
       0.7185979 , 0.49352026, 0.1214813 , 0.7401178 , 0.09666443],
      dtype=float32)>

### one hot encoding tensors

In [208]:
some_list = [0,3,5,2]
tf.one_hot(some_list, depth=9)

<tf.Tensor: shape=(4, 9), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [206]:
tf.one_hot(some_list, on_value="test", off_value="offtest", depth=4)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'test', b'offtest', b'offtest', b'offtest'],
       [b'offtest', b'offtest', b'offtest', b'test'],
       [b'offtest', b'offtest', b'offtest', b'offtest'],
       [b'offtest', b'offtest', b'test', b'offtest']], dtype=object)>

#### Math operation more

In [209]:
I = tf.range(0,10)

In [210]:
tf.square(I)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [212]:
tf.sqrt(tf.cast(I, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [214]:
tf.math.log(tf.cast(I, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986122, 1.3862944, 1.6094378,
       1.7917594, 1.94591  , 2.0794415, 2.1972246], dtype=float32)>

#### NUMPY

In [215]:
J = tf.constant(np.array([1,2,3,4]))

In [216]:
np.array(J)

array([1, 2, 3, 4])

In [217]:
J.numpy()

array([1, 2, 3, 4])

### tf created using numpy array  are float64

## GPU compare

In [222]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]